### ISSUE TITLE
Cant spawn pet in MM version MythicMobs-5.0.0-SNAPSHOT.jar dev build 4051

### ISSUE THREAD

**Issue by honnisha** [MC-Models/mcpets#4]
Error:
```[22:50:55] [Server thread/INFO]: BunnyHonni issued server command: /pets
[22:50:55] [Server thread/INFO]: pets
[22:50:57] [Server thread/ERROR]: Could not pass event InventoryClickEvent to MCPets v1.0.0
java.lang.NullPointerException: Cannot invoke "io.lumine.xikage.mythicmobs.mobs.ActiveMob.getEntity()" because the return value of "io.lumine.xikage.mythicmobs.mobs.MythicMob.spawn(io.lumine.xikage.mythicmobs.adapters.AbstractLocation, double, io.lumine.xikage.mythicmobs.mobs.entities.SpawnReason)" is null
        at io.lumine.xikage.mythicmobs.api.bukkit.BukkitAPIHelper.spawnMythicMob(BukkitAPIHelper.java:85) ~[MythicMobs-5.0.0-SNAPSHOT_4051.jar:?]
        at io.lumine.xikage.mythicmobs.api.bukkit.BukkitAPIHelper.spawnMythicMob(BukkitAPIHelper.java:69) ~[MythicMobs-5.0.0-SNAPSHOT_4051.jar:?]
        at fr.nocsy.mcpets.data.Pet.spawn(Pet.java:221) ~[mcpets 1.0.1.jar:?]
        at fr.nocsy.mcpets.data.Pet.spawn(Pet.java:402) ~[mcpets 1.0.1.jar:?]
        at fr.nocsy.mcpets.data.Pet.spawnWithMessage(Pet.java:307) ~[mcpets 1.0.1.jar:?]
        at fr.nocsy.mcpets.listeners.PetMenuListener.click(PetMenuListener.java:46) ~[mcpets 1.0.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor333.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1565]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2924) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1420) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1499) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1294) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by AlexandreChaussard** [comment]
Version issue, check latest builds =)
